services:
  - type: web
    name: student-event-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./public
